title: A New Ruby Toolbox — Resources
description: Hello Kiwi Ruby! Thanks for listening to me talk about our new tools for Ruby web app development <3 Want to learn more? Here are some resources to get you started.
show_downloads: false
theme: jekyll-theme-minimal
